name: darkan
title: Darkan
version: '1.0.1'
summary: An open-source 2012 Runescape emulation server.
description: |
  Darkan is an open-source 2012 Runescape emulation server aimed towards recreating the game the way it was back in 2012.
  It features official servers, community-run servers, as well as open development servers for people who want to learn to
  contribute to the project. None of these servers are affiliated with Jagex/Runescape and there are no options to purchase
  anything.
  
  If you would like to contribute to the project, please visit the GitHub repository at https://github.com/DarkanRS/world-server.

base: core18
confinement: strict

apps:
  freeplane:
    extensions:
      - gnome-3-28
    command: java -jar client.jar
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - cups-control

parts:
  darkan:
    plugin: gradle
    source: https://github.com/DarkanRS/client-loader.git
    source-tag: master
    gradle-version: '7.1.1'
    gradle-output-dir: BIN
    gradle-options: [buildJar, -xtest, -xcreateGitTag]
    override-build: |
      snapcraftctl build
      cp build/lib/MyJar*.jar $SNAPCRAFT_PART_INSTALL/client.jar